apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 2
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - name: my-nginx
        # do NOT DO this ; use specific tag (as in 'version') instead:
        image: nginx:stable
        resources:
          requests:
            memory: "4Mi"
            cpu: "125m"
          limits:
            memory: "32Mi"
            cpu: "250m"
        ports:
        - containerPort: 80

