apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    run: my-nginx
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    run: my-nginx
  # not using type: LoadBalancer when using ingress rules :
  # (service then gets exposed by our nginx ingress controller automatically)
  #type: LoadBalancer

